### PR TITLE
Minor documentation tweaks

### PR DESCRIPTION
**Pull request by allaway**
I was reading through the documentation and found a couple of things that could be changed. 

I saw the contributing guidelines a bit too late and I based this on `master`. Since this just touches the docs and no code, hopefully this is ok, but please let me know if you'd like me to PR against `develop` instead.

### CODE REVIEW

**Review by ChristopherEeles — APPROVED** [review]
Hi @allaway,

Thanks for catching that. The Creating a PharmacoSet vignette is actually a bit out dated. We are planning a rewrite, but are implementing some major changes in the constructor and data structure we need to complete first.

Best,
Chris

**Review by ChristopherEeles — APPROVED** [review]

**Comment by ChristopherEeles** [comment]
As long as our automated checks pass I will merge this.

Thanks again for contributing.

**Comment by ChristopherEeles** [comment]
Our CI/CD was broken and it looks like pushing to master doesn't affect your pull request.

I am going to merge anyway, since your changes shouldn't break anything.

Best,
Christopher Eeles
Software Developer
BHK Lab | PM-Research | UHN

**Comment by allaway** [comment]
Thanks @ChristopherEeles for the quick review and merge!

**Comment by ChristopherEeles** [comment]
No problem. We are excited to see community members contributing to the improvement of PharmacoGx!

**Pull request merged**
